### ISSUE TITLE
Query by ObjectId ?

### ISSUE THREAD

**Issue by michaelpimentel88** [rouanw/mongo-csv#2]
how do I query by ObjectId?
I try
```
"query" : { "_id": "ObjectId('5adff54537b87f441f9075bd')" }
```
and it doesnt work.
I am perhaps doing something wrong.
also can I do all queries and aggregations?

**Comment by rouanw** [comment]
Hi @michaelpimentel88. Thanks for asking 😄. Querying by `ObjectId` is not currently supported - I'll take a look at adding it as it should be simple enough.

`mongo-csv` currently only supports `find` queries, but may support more in future.

**Comment by michaelpimentel88** [comment]
Ill take a look if your open to PR's

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by rouanw** [comment]
@michaelpimentel88 please try `mongo-csv@2.1.0` - it will now allow you to query by `ObjectID`:

```js
{
  // rest of config.json
  "query" : { "_id": "5adff54537b87f441f9075bd" }
}
```

No need to wrap it in an `ObjectID` constructor because that doesn't mean much in json - `mongo-csv` will use the field name to determine whether to convert it into a CSV.

(This is behaviour we may need to change down the line to support aggregates and/or a JavaScript API, but this will do the trick for now.)

**Comment by michaelpimentel88** [comment]
That was my next question aggregates...lol

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by rouanw** [comment]
Hi @michaelpimentel88. `mongo-csv@2.2.1` now supports aggregates. Let me know if it works for you!

Details in the README: https://github.com/rouanw/mongo-csv#config.
